import { BuildingData } from './components/BuildingCard';

export const mockBuildings: BuildingData[] = [
  {
    id: '1',
    name: '東京オフィスセンターロ',
    type: 'オフィス',
    acquisitionDate: '2024/11/02',
    capRate: 5.2,
    evaluationAmount: 21,
    occupancyRate: 89,
  },
  {
    id: '2',
    name: '東京オフィスセンターロ',
    type: 'オフィス',
    acquisitionDate: '2024/11/02',
    capRate: 5.2,
    evaluationAmount: 21,
    occupancyRate: 89,
  },
  {
    id: '3',
    name: '東京オフィスセンターロ',
    type: 'オフィス',
    acquisitionDate: '2024/11/02',
    capRate: 5.2,
    evaluationAmount: 21,
    occupancyRate: 89,
  },
  {
    id: '4',
    name: '東京オフィスセンターロ',
    type: 'オフィス',
    acquisitionDate: '2024/11/02',
    capRate: 5.2,
    evaluationAmount: 21,
    occupancyRate: 89,
  },
  {
    id: '5',
    name: '東京オフィスセンターロ',
    type: 'オフィス',
    acquisitionDate: '2024/11/02',
    capRate: 5.2,
    evaluationAmount: 21,
    occupancyRate: 89,
  },
  {
    id: '6',
    name: '東京オフィスセンターロ',
    type: 'オフィス',
    acquisitionDate: '2024/11/02',
    capRate: 5.2,
    evaluationAmount: 21,
    occupancyRate: 89,
  },
  {
    id: '7',
    name: '大阪オフィスタワー',
    type: 'オフィス',
    acquisitionDate: '2024/10/15',
    capRate: 4.8,
    evaluationAmount: 18,
    occupancyRate: 92,
  },
  {
    id: '8',
    name: '名古屋商業センター',
    type: '商業施設',
    acquisitionDate: '2024/09/20',
    capRate: 4.5,
    evaluationAmount: 15,
    occupancyRate: 95,
  },
  {
    id: '9',
    name: '福岡ホテルプラザ',
    type: 'ホテル',
    acquisitionDate: '2024/08/10',
    capRate: 5.5,
    evaluationAmount: 12,
    occupancyRate: 78,
  },
  {
    id: '10',
    name: '札幌レジデンス',
    type: '住宅',
    acquisitionDate: '2024/07/05',
    capRate: 3.8,
    evaluationAmount: 9,
    occupancyRate: 97,
  },
]; 